version: '3.3'

## set these in your .env:
# AWS_PROFILE=<profile> (if needed)
# ANSIBLE_VAULT_PASSWORD=*** (see "muse-infra vault" shared note in lastpass)

services:
   digops-stacks-container:
     image: meredithdigops/digops-stacks:latest
     volumes:
       - $HOME/.aws/:/root/.aws/
       - ./:/root/project/
     working_dir: /root/project/
     env_file: .env
