---
version: 2
jobs:
  deploy_base:
    docker:
      - image: meredithdigops/digops-stacks:latest
    steps:
      - checkout
      - run:
         name: Change Directory
         command: 'chmod 766 -R ./'
      - run:
          name: Create SG Group
          no_output_timeout: 45m
          command: './scripts/deploy_sg.sh'
  # deploy_env:
    # docker:
      # - image: meredithdigops/digops-stacks:latest
    # steps:
      # - checkout
      # - run:
          # name: CloudFormation Lint
          # command: './scripts/lint.sh'
      # - run:
          # name: Change Directory
          # command: 'cd /project/scripts'    
      # - run:
          # name: Create SG environment
          # no_output_timeout: 45m
          # command: 'sh deploy_sg.sh'
#      - run:
#          name: Create API Gateway
#          no_output_timeout: 15m
#          command: './scripts/deploy_onecms_api.sh'
#      - run:
#          name: Create Infra Tools (ECS) Resources
#          no_output_timeout: 15m
#          command: './scripts/deploy_onecms_tools.sh'

workflows:
  version: 2
  build:
    jobs:
      - deploy_base
      
          
